name: Bug Report
description: Report a bug in CoreTuff
title: "[Bug]: "
labels:
  - bug

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report for CoreTuff!

  - type: textarea
    id: bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of the issue.
      placeholder: Explain the bug here...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce this behaviour
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: What should happen instead?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Videos
      description: Add screenshots or videos if applicable.

  - type: dropdown
    id: component
    attributes:
      label: Core / Addon
      options:
        - Core
        - Addon
    validations:
      required: true

  - type: input
    id: addon
    attributes:
      label: Addon Name
      placeholder: ExampleAddon

  - type: input
    id: version
    attributes:
      label: CoreTuff Version
      placeholder: 1.0
    validations:
      required: true

  - type: input
    id: mcversion
    attributes:
      label: Minecraft Version
      placeholder: 26.1.2

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any extra information here.
